#ifndef INTERRUPT_HANDLER_H
#define INTERRUPT_HANDLER_H

#include <stdint.h>

#define INT_DESCRIPTION_RESERVED 22
#define INT_DESCRIPTION_EXTERNAL 23
#define INT_DESCRIPTION_UNKNOWN_EXCEPTION 24

enum interrupts
{
    INT_DIVIDE_ERR,
    INT_DEBUG_EXCEPTION,
    INT_NMI_INT,
    INT_BREAKPOINT,
    INT_OVERFLOW,
    INT_BOUND_RANGE_EXCEEDED,
    INT_INVALID_OPCODE,
    INT_NO_MATH_COPROCESSOR,
    INT_DOUBLE_FAULT,
    INT_COPROCESSOR_SEG_OVERRUN,
    INT_INVALID_TSS,
    INT_SEGMENT_NOT_PRESENT,
    INT_STACK_SEGMENT_FAULT,
    INT_GENERAL_PROTECTION_FAULT,
    INT_PAGE_FAULT,
    INT_RESERVED0,
    INT_FPU_FLOATING_POINT_ERR,
    INT_ALIGNMENT_CHECK,
    INT_MACHINE_CHECK,
    INT_SIMD_FLOATING_POINT_EXCEPTION,
    INT_VIRTUALIZATION_EXCEPTION,
    INT_CONTROL_PROTECTION_EXCEPTION,
    INT_RESERVED1,
    INT_RESERVED2,
    INT_RESERVED3,
    INT_RESERVED4,
    INT_RESERVED5,
    INT_RESERVED6,
    INT_RESERVED7,
    INT_RESERVED8,
    INT_RESERVED9,
    INT_RESERVED10,
    INT_EXT_INT0,
    INT_EXT_INT1,
    INT_EXT_INT2,
    INT_EXT_INT3,
    INT_EXT_INT4,
    INT_EXT_INT5,
    INT_EXT_INT6,
    INT_EXT_INT7,
    INT_EXT_INT8,
    INT_EXT_INT9,
    INT_EXT_INT10,
    INT_EXT_INT11,
    INT_EXT_INT12,
    INT_EXT_INT13,
    INT_EXT_INT14,
    INT_EXT_INT15,
    INT_EXT_INT16,
    INT_EXT_INT17,
    INT_EXT_INT18,
    INT_EXT_INT19,
    INT_EXT_INT20,
    INT_EXT_INT21,
    INT_EXT_INT22,
    INT_EXT_INT23,
    INT_EXT_INT24,
    INT_EXT_INT25,
    INT_EXT_INT26,
    INT_EXT_INT27,
    INT_EXT_INT28,
    INT_EXT_INT29,
    INT_EXT_INT30,
    INT_EXT_INT31,
    INT_EXT_INT32,
    INT_EXT_INT33,
    INT_EXT_INT34,
    INT_EXT_INT35,
    INT_EXT_INT36,
    INT_EXT_INT37,
    INT_EXT_INT38,
    INT_EXT_INT39,
    INT_EXT_INT40,
    INT_EXT_INT41,
    INT_EXT_INT42,
    INT_EXT_INT43,
    INT_EXT_INT44,
    INT_EXT_INT45,
    INT_EXT_INT46,
    INT_EXT_INT47,
    INT_EXT_INT48,
    INT_EXT_INT49,
    INT_EXT_INT50,
    INT_EXT_INT51,
    INT_EXT_INT52,
    INT_EXT_INT53,
    INT_EXT_INT54,
    INT_EXT_INT55,
    INT_EXT_INT56,
    INT_EXT_INT57,
    INT_EXT_INT58,
    INT_EXT_INT59,
    INT_EXT_INT60,
    INT_EXT_INT61,
    INT_EXT_INT62,
    INT_EXT_INT63,
    INT_EXT_INT64,
    INT_EXT_INT65,
    INT_EXT_INT66,
    INT_EXT_INT67,
    INT_EXT_INT68,
    INT_EXT_INT69,
    INT_EXT_INT70,
    INT_EXT_INT71,
    INT_EXT_INT72,
    INT_EXT_INT73,
    INT_EXT_INT74,
    INT_EXT_INT75,
    INT_EXT_INT76,
    INT_EXT_INT77,
    INT_EXT_INT78,
    INT_EXT_INT79,
    INT_EXT_INT80,
    INT_EXT_INT81,
    INT_EXT_INT82,
    INT_EXT_INT83,
    INT_EXT_INT84,
    INT_EXT_INT85,
    INT_EXT_INT86,
    INT_EXT_INT87,
    INT_EXT_INT88,
    INT_EXT_INT89,
    INT_EXT_INT90,
    INT_EXT_INT91,
    INT_EXT_INT92,
    INT_EXT_INT93,
    INT_EXT_INT94,
    INT_EXT_INT95,
    INT_EXT_INT96,
    INT_EXT_INT97,
    INT_EXT_INT98,
    INT_EXT_INT99,
    INT_EXT_INT100,
    INT_EXT_INT101,
    INT_EXT_INT102,
    INT_EXT_INT103,
    INT_EXT_INT104,
    INT_EXT_INT105,
    INT_EXT_INT106,
    INT_EXT_INT107,
    INT_EXT_INT108,
    INT_EXT_INT109,
    INT_EXT_INT110,
    INT_EXT_INT111,
    INT_EXT_INT112,
    INT_EXT_INT113,
    INT_EXT_INT114,
    INT_EXT_INT115,
    INT_EXT_INT116,
    INT_EXT_INT117,
    INT_EXT_INT118,
    INT_EXT_INT119,
    INT_EXT_INT120,
    INT_EXT_INT121,
    INT_EXT_INT122,
    INT_EXT_INT123,
    INT_EXT_INT124,
    INT_EXT_INT125,
    INT_EXT_INT126,
    INT_EXT_INT127,
    INT_EXT_INT128,
    INT_EXT_INT129,
    INT_EXT_INT130,
    INT_EXT_INT131,
    INT_EXT_INT132,
    INT_EXT_INT133,
    INT_EXT_INT134,
    INT_EXT_INT135,
    INT_EXT_INT136,
    INT_EXT_INT137,
    INT_EXT_INT138,
    INT_EXT_INT139,
    INT_EXT_INT140,
    INT_EXT_INT141,
    INT_EXT_INT142,
    INT_EXT_INT143,
    INT_EXT_INT144,
    INT_EXT_INT145,
    INT_EXT_INT146,
    INT_EXT_INT147,
    INT_EXT_INT148,
    INT_EXT_INT149,
    INT_EXT_INT150,
    INT_EXT_INT151,
    INT_EXT_INT152,
    INT_EXT_INT153,
    INT_EXT_INT154,
    INT_EXT_INT155,
    INT_EXT_INT156,
    INT_EXT_INT157,
    INT_EXT_INT158,
    INT_EXT_INT159,
    INT_EXT_INT160,
    INT_EXT_INT161,
    INT_EXT_INT162,
    INT_EXT_INT163,
    INT_EXT_INT164,
    INT_EXT_INT165,
    INT_EXT_INT166,
    INT_EXT_INT167,
    INT_EXT_INT168,
    INT_EXT_INT169,
    INT_EXT_INT170,
    INT_EXT_INT171,
    INT_EXT_INT172,
    INT_EXT_INT173,
    INT_EXT_INT174,
    INT_EXT_INT175,
    INT_EXT_INT176,
    INT_EXT_INT177,
    INT_EXT_INT178,
    INT_EXT_INT179,
    INT_EXT_INT180,
    INT_EXT_INT181,
    INT_EXT_INT182,
    INT_EXT_INT183,
    INT_EXT_INT184,
    INT_EXT_INT185,
    INT_EXT_INT186,
    INT_EXT_INT187,
    INT_EXT_INT188,
    INT_EXT_INT189,
    INT_EXT_INT190,
    INT_EXT_INT191,
    INT_EXT_INT192,
    INT_EXT_INT193,
    INT_EXT_INT194,
    INT_EXT_INT195,
    INT_EXT_INT196,
    INT_EXT_INT197,
    INT_EXT_INT198,
    INT_EXT_INT199,
    INT_EXT_INT200,
    INT_EXT_INT201,
    INT_EXT_INT202,
    INT_EXT_INT203,
    INT_EXT_INT204,
    INT_EXT_INT205,
    INT_EXT_INT206,
    INT_EXT_INT207,
    INT_EXT_INT208,
    INT_EXT_INT209,
    INT_EXT_INT210,
    INT_EXT_INT211,
    INT_EXT_INT212,
    INT_EXT_INT213,
    INT_EXT_INT214,
    INT_EXT_INT215,
    INT_EXT_INT216,
    INT_EXT_INT217,
    INT_EXT_INT218,
    INT_EXT_INT219,
    INT_EXT_INT220,
    INT_EXT_INT221,
    INT_EXT_INT222,
    INT_EXT_INT224
};

static char *interrupt_descriptions[25] = {
    "Divide Error.\n",
    "Debug Exception.\n",
    "NMI Interrupt.\n",
    "Breakpoint.\n",
    "Overflow.\n",
    "BOUND Range Exceeded.\n",
    "Invalid Opcode.\n",
    "Device Not Available (No Math Coprocessor).\n",
    "Double Fault: err=%d\n",
    "Coprocessor Segment Overrun.\n",
    "Invalid TSS: err=%d\n",
    "Segment Not Present: err=%d\n",
    "Stack-Segment Fault: err=%d\n",
    "General Protection Fault: err=%d\n",
    "Page Fault: err=%d\n",
    "Intel reserved. This shouldn't come up.\n",
    "x87 FPU Floating-Point Error (Math Fault).\n",
    "Alignment Check: err=%d\n",
    "Machine Check.\n",
    "SIMD Floating-Point Exception.\n",
    "Virtualization Exception.\n"
    "Control Protection Exception: err=%d\n",
    "Reserved for future use. This shouldn't come up.\n",
    "External Interrupt: %d\n",
    "An unknown Exception / Interrupt occured: int=%d, errno=%d\n"
};

struct interrupt_stack_frame
{
    uint64_t r15;
    uint64_t r14;
    uint64_t r13;
    uint64_t r12;
    uint64_t r11;
    uint64_t r10;
    uint64_t r9;
    uint64_t r8;
    uint64_t rbp;
    uint64_t rdi;
    uint64_t rsi;
    uint64_t rdx;
    uint64_t rcx;
    uint64_t rbx;
    uint64_t rax;

    uint64_t interrupt_vector;
    uint64_t error_code;

    uint64_t rip;
    uint64_t cs;
    uint64_t rflags;
    uint64_t rsp_;
    uint64_t ss;
} __attribute__((packed));

void interrupt_handler(struct interrupt_stack_frame *stack);

#endif // INTERRUPT_HANDLER_H