"""
Tool for parsing and analyzing page table dumps generated by kernel/src/memory/paging.c/dump_page_table.

Processes the raw serial output from the kernels page table dump and filters relevant PDPR/PD/PT entries.
Extracts virtual and physical addresses, as well as the page size.
Groups continuous pages into larger memory blocks and outputs a list of these blocks to "page_table_dump.txt".
"""
import os

from dataclasses import dataclass
from typing_extensions import Literal

@dataclass
class Page:
    """
    Information about a page.
    """
    virt_address: int
    phys_address: int
    size: Literal["4kB", "2MB"]

@dataclass
class MemoryBlock:
    """
    A continuous block of pages.
    """
    virt_base_address: int
    phys_base_address: int
    size: int

def filter_input(
    input_file: str,
    output_file: str,
) -> None:
    """
    Remove all lines without either a PT entry or a PD/PDPR entry for a page > 4kB.
    """
    with open(input_file, "r") as fd_input:
        with open(output_file, "w") as fd_output:
            for line in fd_input:
                line = line[8:]

                if not (line.startswith("PT") or line.endswith("(2MB-PAGE)\n") or line.endswith("(1GB-PAGE)\n")):
                    continue

                fd_output.write(line)

def get_phys_address_from_line(
    line: str,
    page_size: Literal["4kB", "2MB"] = "4kB",
) -> int:
    """
    Extract the physical address from a line.
    """
    phys_address: int = -1

    if page_size == "4kB":
        phys_address = int(line.split(": ")[1].replace("\n", ""), base=16)
    elif page_size == "2MB":
        phys_address = int(line.split(": ")[1].split(" ")[0], base=16)
    else:
        raise ValueError(f"Unexpected page size: {page_size}")
    phys_address = phys_address & ~0x7ff
    phys_address = phys_address & 0xffffffffff

    return phys_address

def get_virt_address_from_line(
    line: str,
    page_size: Literal["4kB", "2MB"] = "4kB",
) -> int:
    """
    Extract the virtual address from a line.
    """
    virt_address: int = -1

    line = line.split(": ")[0] # Remove the page table entry from the line. We only need the indices.
    pml4_idx: int
    pdpr_idx: int
    pd_idx: int
    pt_idx: int
    if page_size == "4kB":
        pml4_idx = int(line.split("-")[1])
        pdpr_idx = int(line.split("-")[2])
        pd_idx = int(line.split("-")[3].split("@")[0])
        pt_idx = int(line.split("@")[1])
    elif page_size == "2MB":
        pml4_idx = int(line.split("-")[1])
        pdpr_idx = int(line.split("-")[2].split("@")[0])
        pd_idx = int(line.split("@")[1])
        pt_idx = 0
    else:
        raise ValueError(f"Unexpected page size: {page_size}")

    sign_extension: int = 0xffff if (pml4_idx >> 8) == 1 else 0
    virt_address = (sign_extension << 48) | (pml4_idx << 39) | (pdpr_idx << 30) | (pd_idx << 21) | (pt_idx << 12)

    return virt_address

def get_pages(
    input_file: str,
) -> list[Page]:
    """
    Extract information about the pages.
    """
    pages: list[Page] = []

    with open(input_file, "r") as fd:
        for line in fd:
            if line.startswith("PT"):
                virt = get_virt_address_from_line(line, page_size="4kB")
                phys = get_phys_address_from_line(line, page_size="4kB")
                pages.append(Page(virt_address=virt, phys_address=phys, size="4kB"))
            elif "(2MB-PAGE)" in line:
                virt = get_virt_address_from_line(line, page_size="2MB")
                phys = get_phys_address_from_line(line, page_size="2MB")
                pages.append(Page(virt_address=virt, phys_address=phys, size="2MB"))

    return pages

def get_memory_blocks(
    pages: list[Page],
) -> list[MemoryBlock]:
    """
    Group continuous pages into blocks.
    """
    memory_blocks: list[MemoryBlock] = []

    virt_base_address: int = -1
    phys_base_address: int = -1
    size: int = 0

    last_virt_address: int = -1
    last_phys_address: int = -1
    last_page_size: int = -1

    for page in pages:
        page_size: int = 0x1000 if page.size == "4kB" else 2*(2**20)
        if virt_base_address < 0:
            virt_base_address = page.virt_address
            phys_base_address = page.phys_address
            size = page_size
        elif (page.phys_address - last_phys_address != last_page_size) or (page.virt_address - last_virt_address != last_page_size):
            memory_blocks.append(MemoryBlock(virt_base_address, phys_base_address, size))
            
            virt_base_address = page.virt_address
            phys_base_address = page.phys_address
            size = page_size
        else:
            size = size + page_size

        last_virt_address = page.virt_address
        last_phys_address = page.phys_address
        last_page_size = page_size

    return memory_blocks

if __name__ == "__main__":
    INPUT_FILE: str = os.path.join(os.path.dirname(__file__), "../serial_output")
    WORK_FILE: str = os.path.join(os.path.dirname(__file__), "temp_analyze_pt_dump.txt")
    RESULT_FILE: str = os.path.join(os.path.dirname(__file__), "page_table_dump.txt")

    filter_input(INPUT_FILE, WORK_FILE)

    pages: list[Page] = get_pages(WORK_FILE)
    with open(WORK_FILE, "w") as fd:
        for page in pages:
            fd.write(f"{page.virt_address:x} -> {page.phys_address:x} ({page.size})\n")

    blocks: list[MemoryBlock] = get_memory_blocks(pages)
    with open(RESULT_FILE, "w") as fd:
        for block in blocks:
            fd.write(f"0x{block.virt_base_address:x} -> 0x{block.phys_base_address:x} | {block.size} B\n")